### ISSUE TITLE
Autoscaler not reaching scale 1 if I do HTTP GET and scale was zero

### ISSUE THREAD

**Issue by izaac** [rancher/rio#607]
**Describe the bug**
The autoscaler seems to be going back to 0 very quick so subsequent GET requests after the first one sometimes fails with `no healthy upstream`

**To Reproduce**
1. Create a service with scale range from zero. `rio run --scale=0-11 -p 80 -n ascaler strongmonkey1992/autoscale:testing`
2. Wait until the endpoint is created and the pods are created and then scale is zero
4. Open the Endpoint in the browser once. Do not close the browser tab. (Chrome 77 was used here).
5. If the content was shown correctly wait until the scale is 0 again. 
6. Try again refreshing the browser once.
7. If no error, repeat 5.

I sometimes get the `no healthy upstream` message.

**Expected behavior**

The endpoint responds with the expected content. Every time I do an HTTP GET with a browser. 

**Kubernetes version & type (GKE, on-prem)**: `kubectl version`
```
v1.14.7-gke.10
```
Type:
**Rio version**: `rio info`
```
Rio Version: v0.6.0-alpha.1 (7678d67d)
Rio CLI Version: v0.6.0-alpha.1 (7678d67d)
```
**Additional context**
`rio systemlog`
output:
```
nothing relevant
```

**Comment by izaac** [comment]
This looks as dupe of https://github.com/rancher/rio/issues/584 reported by @rancher-max, please close if this is the case.

**Comment by davidnuzik** [comment]
Also should scale on outgoing requests. (both outbound and inbound)

**Comment by daxmc99** [comment]
This appears to be fixed. I am not seeing any issues and the scale up time has been about 30 sec for the sample image deployed and with images I have tested with. 

Stats for a scale from 0, image pre-pulled. 
```
curl -w "@curl-format.txt" -o /dev/null -s "https://ascaler-v0-default.049910.on-rio.io"
 time_namelookup:  0.032576
       time_connect:  0.032732
    time_appconnect:  0.045256
   time_pretransfer:  0.045323
      time_redirect:  0.000000
 time_starttransfer:  11.383586
                    ----------
         time_total:  11.383646
```

**Comment by daxmc99** [comment]
From a single request point of view from curl this bug is fixed, however there is some finicky behavior in browsers documented in https://github.com/rancher/rio/issues/861. 

This issue has been fixed and there is some more investigation of how browsers perform requests (esp Chrome)

**Comment by rancher-max** [comment]
We noticed this still happens and believe https://github.com/rancher/rio/issues/861#issuecomment-568608839 will resolve the issue. The relevant issue is noted in: https://github.com/rancher/rio/issues/584#issuecomment-547027174.

I did see one "no healthy upstream" message in testing, but it happens less frequently now. The case where I saw it was executing `curl` on the app endpoint for a service many times in succession:
```
$ for x in {1..20} ; do curl https://as-default.xxxxxx.on-rio.io ; done
Hello World
no healthy upstreamHello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
```

**Comment by rancher-max** [comment]
Looks like the `no healthy upstream` error is fixed. This was the case when curling the endpoint multiple times in succession during scaleup. However, the LibreSSL errors still happen, where the service refuses to scale up by using the version endpoint. @daxmc99 has more notes and additional findings to add to this.

```
$ rio ps
NAME             IMAGE                                  ENDPOINT                                             PORTS     SCALE     WEIGHT    CREATED          DETAIL
gh-as            default/gh-as-v07zq2p:ff1ec            https://gh-as-v0-default.yy4yy9.on-rio.io            8080      0         100%      22 minutes ago   
other-as         strongmonkey1992/autoscale:testing     https://other-as-v0-default.yy4yy9.on-rio.io         80        0         100%      23 minutes ago   
as               strongmonkey1992/autoscale:testing     https://as-v0-default.yy4yy9.on-rio.io               80        0         100%      23 minutes ago   
demo             ibuildthecloud/demo:v1                 https://demo-v0-default.yy4yy9.on-rio.io             80        1         100%      24 minutes ago   
amazing-bartik   default/amazing-bartik-v0hdwtm:f8fab   https://amazing-bartik-v0-default.yy4yy9.on-rio.io   80:8080   1         100%      24 minutes ago   
$ curl https://other-as-v0-default.yy4yy9.on-rio.io
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to other-as-v0-default.yy4yy9.on-rio.io:443 
$ for x in {1..20} ; do curl $ rio ps
> NAME             IMAGE                                  ENDPOINT                                             PORTS     SCALE     WEIGHT    CREATED          DETAIL
> gh-as            default/gh-as-v07zq2p:ff1ec            https://gh-as-v0-default.yy4yy9.on-rio.io            8080      0         100%      22 minutes ago   
> other-as         strongmonkey1992/autoscale:testing     https://other-as-v0-default.yy4yy9.on-rio.io         80        0         100%      23 minutes ago   
> as               strongmonkey1992/autoscale:testing     https://as-v0-default.yy4yy9.on-rio.io               80        0         100%      23 minutes ago   
> demo             ibuildthecloud/demo:v1                 https://demo-v0-default.yy4yy9.on-rio.io             80        1         100%      24 minutes ago   
> amazing-bartik   default/amazing-bartik-v0hdwtm:f8fab   https://amazing-bartik-v0-default.yy4yy9.on-rio.io   80:8080   1         100%      24 minutes ago   
$ for x in {1..20} ; do curl https://other-as-default.yy4yy9.on-rio.io ; done
Hi there, I am rio:production6
Hi there, I am rio:production6
Hi there, I am rio:production6
Hi there, I am rio:production6
Hi there, I am rio:production6
Hi there, I am rio:production6
Hi there, I am rio:production6
Hi there, I am rio:production6
Hi there, I am rio:production6
Hi there, I am rio:production6
Hi there, I am rio:production6
Hi there, I am rio:production6
Hi there, I am rio:production6
Hi there, I am rio:production6
Hi there, I am rio:production6
Hi there, I am rio:production6
Hi there, I am rio:production6
Hi there, I am rio:production6
Hi there, I am rio:production6
Hi there, I am rio:production6
```

**Comment by rancher-max** [comment]
Closing in favor of #584
